export const appName = "Hifz Helper";
export const surahs = [
  {
    number: 1,
    name: "Al-Fatihah",
    nameEnglish: "The Opener",
    numberOfAyats: 7,
  },
  {
    number: 2,
    name: "Al-Baqarah",
    nameEnglish: "The Cow",
    numberOfAyats: 286,
  },
  {
    number: 3,
    name: "Ali 'Imran",
    nameEnglish: "Family of Imran",
    numberOfAyats: 200,
  },
  {
    number: 4,
    name: "An-Nisa",
    nameEnglish: "The Women",
    numberOfAyats: 176,
  },
  {
    number: 5,
    name: "Al-Ma'idah",
    nameEnglish: "The Table Spread",
    numberOfAyats: 120,
  },
  {
    number: 6,
    name: "Al-An'am",
    nameEnglish: "The Cattle",
    numberOfAyats: 165,
  },
  {
    number: 7,
    name: "Al-A'raf",
    nameEnglish: "The Heights",
    numberOfAyats: 206,
  },
  {
    number: 8,
    name: "Al-Anfal",
    nameEnglish: "The Spoils of War",
    numberOfAyats: 75,
  },
  {
    number: 9,
    name: "At-Tawbah",
    nameEnglish: "The Repentance",
    numberOfAyats: 129,
  },
  {
    number: 10,
    name: "Yunus",
    nameEnglish: "Jonah",
    numberOfAyats: 109,
  },
  {
    number: 11,
    name: "Hud",
    nameEnglish: "Hud",
    numberOfAyats: 123,
  },
  {
    number: 12,
    name: "Yusuf",
    nameEnglish: "Joseph",
    numberOfAyats: 111,
  },
  {
    number: 13,
    name: "Ar-Ra'd",
    nameEnglish: "The Thunder",
    numberOfAyats: 43,
  },
  {
    number: 14,
    name: "Ibrahim",
    nameEnglish: "Abraham",
    numberOfAyats: 52,
  },
  {
    number: 15,
    name: "Al-Hijr",
    nameEnglish: "The Rocky Tract",
    numberOfAyats: 99,
  },
  {
    number: 16,
    name: "An-Nahl",
    nameEnglish: "The Bee",
    numberOfAyats: 128,
  },
  {
    number: 17,
    name: "Al-Isra",
    nameEnglish: "The Night Journey",
    numberOfAyats: 111,
  },
  {
    number: 18,
    name: "Al-Kahf",
    nameEnglish: "The Cave",
    numberOfAyats: 110,
  },
  {
    number: 19,
    name: "Maryam",
    nameEnglish: "Mary",
    numberOfAyats: 98,
  },
  {
    number: 20,
    name: "Taha",
    nameEnglish: "Ta-Ha",
    numberOfAyats: 135,
  },
  {
    number: 21,
    name: "Al-Anbya",
    nameEnglish: "The Prophets",
    numberOfAyats: 112,
  },
  {
    number: 22,
    name: "Al-Hajj",
    nameEnglish: "The Pilgrimage",
    numberOfAyats: 78,
  },
  {
    number: 23,
    name: "Al-Mu'minun",
    nameEnglish: "The Believers",
    numberOfAyats: 118,
  },
  {
    number: 24,
    name: "An-Nur",
    nameEnglish: "The Light",
    numberOfAyats: 64,
  },
  {
    number: 25,
    name: "Al-Furqan",
    nameEnglish: "The Criterion",
    numberOfAyats: 77,
  },
  {
    number: 26,
    name: "Ash-Shu'ara",
    nameEnglish: "The Poets",
    numberOfAyats: 227,
  },
  {
    number: 27,
    name: "An-Naml",
    nameEnglish: "The Ant",
    numberOfAyats: 93,
  },
  {
    number: 28,
    name: "Al-Qasas",
    nameEnglish: "The Stories",
    numberOfAyats: 88,
  },
  {
    number: 29,
    name: "Al-'Ankabut",
    nameEnglish: "The Spider",
    numberOfAyats: 69,
  },
  {
    number: 30,
    name: "Ar-Rum",
    nameEnglish: "The Romans",
    numberOfAyats: 60,
  },
  {
    number: 31,
    name: "Luqman",
    nameEnglish: "Luqman",
    numberOfAyats: 34,
  },
  {
    number: 32,
    name: "As-Sajdah",
    nameEnglish: "The Prostration",
    numberOfAyats: 30,
  },
  {
    number: 33,
    name: "Al-Ahzab",
    nameEnglish: "The Combined Forces",
    numberOfAyats: 73,
  },
  {
    number: 34,
    name: "Saba",
    nameEnglish: "Sheba",
    numberOfAyats: 54,
  },
  {
    number: 35,
    name: "Fatir",
    nameEnglish: "Originator",
    numberOfAyats: 45,
  },
  {
    number: 36,
    name: "Ya-Sin",
    nameEnglish: "Ya Sin",
    numberOfAyats: 83,
  },
  {
    number: 37,
    name: "As-Saffat",
    nameEnglish: "Those who set the Ranks",
    numberOfAyats: 182,
  },
  {
    number: 38,
    name: "Sad",
    nameEnglish: "The Letter Saad",
    numberOfAyats: 88,
  },
  {
    number: 39,
    name: "Az-Zumar",
    nameEnglish: "The Troops",
    numberOfAyats: 75,
  },
  {
    number: 40,
    name: "Ghafir",
    nameEnglish: "The Forgiver",
    numberOfAyats: 85,
  },
  {
    number: 41,
    name: "Fussilat",
    nameEnglish: "Explained in Detail",
    numberOfAyats: 54,
  },
  {
    number: 42,
    name: "Ash-Shuraa",
    nameEnglish: "The Consultation",
    numberOfAyats: 53,
  },
  {
    number: 43,
    name: "Az-Zukhruf",
    nameEnglish: "The Ornaments of Gold",
    numberOfAyats: 89,
  },
  {
    number: 44,
    name: "Ad-Dukhan",
    nameEnglish: "The Smoke",
    numberOfAyats: 59,
  },
  {
    number: 45,
    name: "Al-Jathiyah",
    nameEnglish: "The Crouching",
    numberOfAyats: 37,
  },
  {
    number: 46,
    name: "Al-Ahqaf",
    nameEnglish: "The Wind-Curved Sandhills",
    numberOfAyats: 35,
  },
  {
    number: 47,
    name: "Muhammad",
    nameEnglish: "Muhammad",
    numberOfAyats: 38,
  },
  {
    number: 48,
    name: "Al-Fath",
    nameEnglish: "The Victory",
    numberOfAyats: 29,
  },
  {
    number: 49,
    name: "Al-Hujurat",
    nameEnglish: "The Rooms",
    numberOfAyats: 18,
  },
  {
    number: 50,
    name: "Qaf",
    nameEnglish: "The Letter Qaf",
    numberOfAyats: 45,
  },
  {
    number: 51,
    name: "Adh-Dhariyat",
    nameEnglish: "The Winnowing Winds",
    numberOfAyats: 60,
  },
  {
    number: 52,
    name: "At-Tur",
    nameEnglish: "The Mount",
    numberOfAyats: 49,
  },
  {
    number: 53,
    name: "An-Najm",
    nameEnglish: "The Star",
    numberOfAyats: 62,
  },
  {
    number: 54,
    name: "Al-Qamar",
    nameEnglish: "The Moon",
    numberOfAyats: 55,
  },
  {
    number: 55,
    name: "Ar-Rahman",
    nameEnglish: "The Beneficent",
    numberOfAyats: 78,
  },
  {
    number: 56,
    name: "Al-Waqi'ah",
    nameEnglish: "The Inevitable",
    numberOfAyats: 96,
  },
  {
    number: 57,
    name: "Al-Hadid",
    nameEnglish: "The Iron",
    numberOfAyats: 29,
  },
  {
    number: 58,
    name: "Al-Mujadila",
    nameEnglish: "The Pleading Woman",
    numberOfAyats: 22,
  },
  {
    number: 59,
    name: "Al-Hashr",
    nameEnglish: "The Exile",
    numberOfAyats: 24,
  },
  {
    number: 60,
    name: "Al-Mumtahanah",
    nameEnglish: "She that is to be examined",
    numberOfAyats: 13,
  },
  {
    number: 61,
    name: "As-Saf",
    nameEnglish: "The Ranks",
    numberOfAyats: 14,
  },
  {
    number: 62,
    name: "Al-Jumu'ah",
    nameEnglish: "The Congregation, Friday",
    numberOfAyats: 11,
  },
  {
    number: 63,
    name: "Al-Munafiqun",
    nameEnglish: "The Hypocrites",
    numberOfAyats: 11,
  },
  {
    number: 64,
    name: "At-Taghabun",
    nameEnglish: "The Mutual Disillusion",
    numberOfAyats: 18,
  },
  {
    number: 65,
    name: "At-Talaq",
    nameEnglish: "The Divorce",
    numberOfAyats: 12,
  },
  {
    number: 66,
    name: "At-Tahrim",
    nameEnglish: "The Prohibition",
    numberOfAyats: 12,
  },
  {
    number: 67,
    name: "Al-Mulk",
    nameEnglish: "The Sovereignty",
    numberOfAyats: 30,
  },
  {
    number: 68,
    name: "Al-Qalam",
    nameEnglish: "The Pen",
    numberOfAyats: 52,
  },
  {
    number: 69,
    name: "Al-Haqqah",
    nameEnglish: "The Reality",
    numberOfAyats: 52,
  },
  {
    number: 70,
    name: "Al-Ma'arij",
    nameEnglish: "The Ascending Stairways",
    numberOfAyats: 44,
  },
  {
    number: 71,
    name: "Nuh",
    nameEnglish: "Noah",
    numberOfAyats: 28,
  },
  {
    number: 72,
    name: "Al-Jinn",
    nameEnglish: "The Jinn",
    numberOfAyats: 28,
  },
  {
    number: 73,
    name: "Al-Muzzammil",
    nameEnglish: "The Enshrouded One",
    numberOfAyats: 20,
  },
  {
    number: 74,
    name: "Al-Muddaththir",
    nameEnglish: "The Cloaked One",
    numberOfAyats: 56,
  },
  {
    number: 75,
    name: "Al-Qiyamah",
    nameEnglish: "The Resurrection",
    numberOfAyats: 40,
  },
  {
    number: 76,
    name: "Al-Insan",
    nameEnglish: "The Man",
    numberOfAyats: 31,
  },
  {
    number: 77,
    name: "Al-Mursalat",
    nameEnglish: "The Emissaries",
    numberOfAyats: 50,
  },
  {
    number: 78,
    name: "An-Naba",
    nameEnglish: "The Tidings",
    numberOfAyats: 40,
  },
  {
    number: 79,
    name: "An-Nazi'at",
    nameEnglish: "Those who drag forth",
    numberOfAyats: 46,
  },
  {
    number: 80,
    name: "'Abasa",
    nameEnglish: "He Frowned",
    numberOfAyats: 42,
  },
  {
    number: 81,
    name: "At-Takwir",
    nameEnglish: "The Overthrowing",
    numberOfAyats: 29,
  },
  {
    number: 82,
    name: "Al-Infitar",
    nameEnglish: "The Cleaving",
    numberOfAyats: 19,
  },
  {
    number: 83,
    name: "Al-Mutaffifin",
    nameEnglish: "The Defrauding",
    numberOfAyats: 36,
  },
  {
    number: 84,
    name: "Al-Inshiqaq",
    nameEnglish: "The Sundering",
    numberOfAyats: 25,
  },
  {
    number: 85,
    name: "Al-Buruj",
    nameEnglish: "The Mansions of the Stars",
    numberOfAyats: 22,
  },
  {
    number: 86,
    name: "At-Tariq",
    nameEnglish: "The Nightcommer",
    numberOfAyats: 17,
  },
  {
    number: 87,
    name: "Al-A'la",
    nameEnglish: "The Most High",
    numberOfAyats: 19,
  },
  {
    number: 88,
    name: "Al-Ghashiyah",
    nameEnglish: "The Overwhelming",
    numberOfAyats: 26,
  },
  {
    number: 89,
    name: "Al-Fajr",
    nameEnglish: "The Dawn",
    numberOfAyats: 30,
  },
  {
    number: 90,
    name: "Al-Balad",
    nameEnglish: "The City",
    numberOfAyats: 20,
  },
  {
    number: 91,
    name: "Ash-Shams",
    nameEnglish: "The Sun",
    numberOfAyats: 15,
  },
  {
    number: 92,
    name: "Al-Layl",
    nameEnglish: "The Night",
    numberOfAyats: 21,
  },
  {
    number: 93,
    name: "Ad-Duhaa",
    nameEnglish: "The Morning Hours",
    numberOfAyats: 11,
  },
  {
    number: 94,
    name: "Ash-Sharh",
    nameEnglish: "The Relief",
    numberOfAyats: 8,
  },
  {
    number: 95,
    name: "At-Tin",
    nameEnglish: "The Fig",
    numberOfAyats: 8,
  },
  {
    number: 96,
    name: "Al-'Alaq",
    nameEnglish: "The Clot",
    numberOfAyats: 19,
  },
  {
    number: 97,
    name: "Al-Qadr",
    nameEnglish: "The Power",
    numberOfAyats: 5,
  },
  {
    number: 98,
    name: "Al-Bayyinah",
    nameEnglish: "The Clear Proof",
    numberOfAyats: 8,
  },
  {
    number: 99,
    name: "Az-Zalzalah",
    nameEnglish: "The Earthquake",
    numberOfAyats: 8,
  },
  {
    number: 100,
    name: "Al-'Adiyat",
    nameEnglish: "The Courser",
    numberOfAyats: 11,
  },
  {
    number: 101,
    name: "Al-Qari'ah",
    nameEnglish: "The Calamity",
    numberOfAyats: 11,
  },
  {
    number: 102,
    name: "At-Takathur",
    nameEnglish: "The Rivalry in world increase",
    numberOfAyats: 8,
  },
  {
    number: 103,
    name: "Al-'Asr",
    nameEnglish: "The Declining Day",
    numberOfAyats: 3,
  },
  {
    number: 104,
    name: "Al-Humazah",
    nameEnglish: "The Traducer",
    numberOfAyats: 9,
  },
  {
    number: 105,
    name: "Al-Fil",
    nameEnglish: "The Elephant",
    numberOfAyats: 5,
  },
  {
    number: 106,
    name: "Quraysh",
    nameEnglish: "Quraysh",
    numberOfAyats: 4,
  },
  {
    number: 107,
    name: "Al-Ma'un",
    nameEnglish: "The Small kindnesses",
    numberOfAyats: 7,
  },
  {
    number: 108,
    name: "Al-Kawthar",
    nameEnglish: "The Abundance",
    numberOfAyats: 3,
  },
  {
    number: 109,
    name: "Al-Kafirun",
    nameEnglish: "The Disbelievers",
    numberOfAyats: 6,
  },
  {
    number: 110,
    name: "An-Nasr",
    nameEnglish: "The Divine Support",
    numberOfAyats: 3,
  },
  {
    number: 111,
    name: "Al-Masad",
    nameEnglish: "The Palm Fiber",
    numberOfAyats: 5,
  },
  {
    number: 112,
    name: "Al-Ikhlas",
    nameEnglish: "The Sincerity",
    numberOfAyats: 4,
  },
  {
    number: 113,
    name: "Al-Falaq",
    nameEnglish: "The Daybreak",
    numberOfAyats: 5,
  },
  {
    number: 114,
    name: "An-Nas",
    nameEnglish: "Mankind",
    numberOfAyats: 6,
  },
];

export function generateAllFileNames() {
  const links: string[] = [];

  surahs.forEach(({ number: surahNumber, numberOfAyats }) => {
    for (let ayatNumber = 1; ayatNumber < numberOfAyats; ayatNumber++) {
      const track: string = `${surahNumber
        .toString()
        .padStart(3, "0")}${ayatNumber.toString().padStart(3, "0")}`;

      const link = `https://mirrors.quranicaudio.com/muqri/alafasi/opus/${track}.opus`;
      links.push(link);
    }
  });

  return links;
}

// console.log(generateAllFileNames());
